[package]
name = "otp-stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = {version="1.12.0",default-features=false}
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
sha3 = {version="0.10.8",default-features=false}

[features]
std=["either/use_std","sha3/std"]
default=["std"]
